# Postgres DB
spring:
    main:
        web-application-type: servlet
    port: 8080
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
    application:
        name: ai-genre
    data:
        redis:
            cache:
                host: ${REDIS_CACHE_HOST}
                port: ${REDIS_CACHE_PORT}
                database: 0
                ttl: 3600000
            broker:
                host: ${REDIS_BROKER_HOST}
                port: ${REDIS_BROKER_PORT}
                database: 0
                ttl: 3600000
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            initialization-fail-time: 10000
    flyway:
        location: classpath:db/migration
    http:
        allowed-origins: ${HTTP_ALLOWED_ORIGINS:http://localhost}
    websocket:
        allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost}
    jpa:
        hibernate:
            # Hibernate only validates the db format matches the java code (flyway creates the db)
            ddl-auto: validate
    grpc:
        client:
            channels:
                grpc-server:
                    address: ${GRPC_HOST}