# noble needed for glibc for protoc
FROM maven:3.9.16-eclipse-temurin-26-noble AS builder
WORKDIR /app

# Copy only the pom.xml to leverage Docker cache for dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code and build the package (skips tests)
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:26-jre-alpine
WORKDIR /app

# Use builder values
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

# Create user group
RUN addgroup --system --gid 1001 appgroup && \
    adduser --system --ingroup appgroup --uid 1001 appuser

USER appuser

ENTRYPOINT ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "app.jar"]