# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"O\n\tFileChunk\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tfile_hash\x18\x02 \x01(\t\x12\r\n\x05\x63hunk\x18\x03 \x01(\x0c\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x10InferenceService\x12.\n\nStreamFile\x12\n.FileChunk\x1a\x10.EnqueueResponse\"\x00(\x01\x42\x30\n\x1c\x64ylanlederman.ai_genre.protoB\x0eInferenceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034dylanlederman.ai_genre.protoB\016InferenceProtoP\001'
  _globals['_FILECHUNK']._serialized_start=19
  _globals['_FILECHUNK']._serialized_end=98
  _globals['_ENQUEUERESPONSE']._serialized_start=100
  _globals['_ENQUEUERESPONSE']._serialized_end=134
  _globals['_INFERENCESERVICE']._serialized_start=136
  _globals['_INFERENCESERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
