# Build stage
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve stage
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Get nginx config (Uses special nginx templates/ directory)
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]