global:
  scrape_interval: 15s
scrape_configs:

  - job_name: prometheus
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "spring-backend:8080" ]

  - job_name: redis
    static_configs:
      - targets:
        - redis://redis-cache:6379
        - redis://redis-broker:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  - job_name: redis-exporter
    static_configs:
      - targets:
        - redis-exporter:9121

  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
  
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: [ 'celery-broker:15692' ]
  
  - job_name: minio
    metrics_path: /minio/metrics/v3/api/requests
    static_configs:
      - targets: [ 'minio-storage:9000' ]
  
  - job_name: celery-worker
    metrics_path: /metrics
    static_configs:
      - targets: [ 'celery-exporter:9540' ]
  
  - job_name: celery-grpc
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grpc-server:8000' ]