# gRPC Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: grpc
  namespace: celery
spec:
  type: ClusterIP
  selector:
    app: grpc
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
--- # gRPC Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  namespace: celery
  labels:
    app: grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: <grpc-image>
        ports:
        - containerPort: 50051
        envFrom:
        - secretRef:
            name: <secret-name>
