apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworker
  namespace: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: celery
        image: dylhead/ai-genre-celery-cpu # remove cpu if using gpu
        env:
          - name: NUMBA_CACHE_DIR
            value: /tmp/numba_cache
        envFrom:
        - secretRef:
            name: celery
        # Gpu if using gpu
        # resources:
          # limits:
            # nvidia.com/gpu: 1
        volumeMounts:
          - name: minio-ca
            mountPath: /etc/minio/certs
        livenessProbe:
          exec:
            command: ["bash", "-c", "celery inspect ping -d celery@$HOSTNAME | grep -q pong"]
          initialDelaySeconds: 45
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["bash", "-c", "celery inspect ping -d celery@$HOSTNAME | grep -q pong"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
      volumes:
        - name: minio-ca
          secret:
            secretName: minio-ca