version: v1
nodes:
    - name: great-leafroller
      drives:
        - id: 8:13$LU2Bpj59YVDrHdWvJUSc0jsYKv3sEtzCqIcLses5Oeo=
          name: sda13
          size: 1072693760
          make: Msft Virtual_Disk (Part 13)
          fs: ext4
          select: "no"
    - name: worker
      drives:
        - id: 252:0$IRC5RFcK7Lk6P+EPRJwlj5p0DY6t56NMn8EfoZT1BEY=
          name: dm-0
          size: 5368709120
          make: directpv-disk1
          select: "yes"
        - id: 8:13$G/CiQw4zjh3zlhS0Pq2sSDBIDXSqSW6EsyTzm0Oo2/Y=
          name: sda13
          size: 1072693760
          make: Msft Virtual_Disk (Part 13)
          fs: ext4
          select: "no"
