# Postgres Secret (Remove this and create secrets in cmd line in production)
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: backend
  labels:
    cnpg.io/reload: "" # Instructs CNPG to auto-reload on changes
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password
  database: genre_db
---
# Postgres DB
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: backend
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  affinity: {}
  bootstrap:
    initdb:
      database: genre_db
      owner: user
      secret:
        name: postgres
  
  ephemeralVolumesSizeLimit:
    temporaryData: 2Gi
    shm: 1Gi
  storage:
    size: 5Gi # 5 Gibibytes of storage
    # Use default storageClass, can add local-path and enforce
    # storageClass: local-path