objectStore:
  name: minio
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: directpv-min-io
          resources:
            requests:
              storage: 2Gi
  services:
    minio:
      serviceType: NodePort
      nodePort: 31000
  externalCertSecret:
    - name: minio-tls
      type: cert-manager.io/v1