apiVersion: aistor.min.io/v1
kind: ObjectStore
metadata:
  name: minio
  namespace: celery
  labels:
    app: minio
spec:
  certificates:
    disableAutoCert: true
    server:
    - name: minio-tls
      type: cert-manager.io/v1
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce # Only one node has read/write access
          storageClassName: directpv-min-io
          resources:
            requests:
              storage: 2Gi # 2 Gibibytes