# Frontend ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dylhead/ai-genre-frontend
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_WEBSOCKET_PROTOCOL
            value: "wss"
          - name: BACKEND_URL # nginx injects env vars for the backend url. Here it points to the gateway
            value: "http://backend.backend.svc.cluster.local:8080"