apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: celerybroker
  namespace: celery
  labels:
    app: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  persistence:
    storage: 2Gi
  secretBackend:
    externalSecret:
      name: rabbitmq